### ISSUE TITLE
ImportError: dynamic module does not define init function 

### ISSUE THREAD

**Issue by mtrth** [philkr/lpo#26]
I followed the instructions in the readme and compiled with -DUSE_PYTHON=2 , when I do bash eval_all.sh I get error:

Traceback (most recent call last):
File "train_lpo.py", line 31, in
from lpo import *
File "/home/revathy/lpo-release/src/lpo.py", line 45, in
from python.lpo import *
ImportError: dynamic module does not define init function (PyInit_lpo)

hope you could help me. Thanks.

**Comment by philkr** [comment]
Is the lpo module built? Is there an lpo.so? Are you building lpo with the same version of python as you're calling it?

**Comment by mtrth** [comment]
ya I did
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DDATA_DIR=/path/to/datasets -DUSE_PYTHON=ON
make -j9

also I have lpo.so in build/lib/python.

$ python version 
 Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

**Comment by philkr** [comment]
I have only gotten this error, when I build lpo with boost-python3 and run it with python2 or vice versa.

**Comment by liao1995** [comment]
i have gotten this error too, if you build lpo with python2, you need modify python3 to python2 in file eval_all.sh:
`P=${PYTHON:=python2}`

**Comment by monajalal** [comment]
not 100% related but fairly related. Can you please have a look?
I get the following error when running the code given in this repository https://github.com/paulu/material-seg :

```
[jalal@goku material-seg]$ /scratch/sjn-p2/anaconda/anaconda2/bin/python demo.py images/1189.jpg
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    import densecrf_matclass.densecrf # this one ignores the "other" category
  File "/scratch/mona/download/cs542/material-seg/densecrf_matclass/densecrf.py", line 6, in <module>
    from krahenbuhl2013.krahenbuhl2013 import DenseCRF
ImportError: dynamic module does not define init function (initkrahenbuhl2013)
```
I am not aware how this error should be fixed. Additional possible useful information can be found here https://github.com/paulu/material-seg/issues/4
