### ISSUE TITLE
eval_box raises exception with demonstration models

### ISSUE THREAD

**Issue by rodrigob** [philkr/lpo#7]
Following the readme steps, running `eval_box.py` also raises an exception.

```
python eval_box.py test.txt ../models/lpo_VOC_0.1.dat
Traceback (most recent call last):
  File "eval_box.py", line 57, in <module>
    bo,pool_s = evaluateBox( prop, over_segs, boxes, name='(tst)' )
  File "eval_box.py", line 43, in evaluateBox
    print( "LPO %05s & %d & %0.3f & %0.3f & %0.3f & %0.3f & %0.3f \\\\"%(name,np.nanmean(pool_s),np.mean(bo),np.mean(bo>=0.5), np.mean(bo>=0.7), np.mean(bo>=0.9), np.mean(2*np.maximum(bo-0.5,0)) ) )
UnboundLocalError: local variable 'pool_s' referenced before assignment
```

both `bo, pool_s` are dangerously non-initialized.

I guess something else is off, but I cannot quite figure out what, since none of the scripts seems to work as expected.

**Comment by rodrigob** [comment]
Fixing the data_dir path fixed this issue (as indicated in #6).
